In [71]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [72]:
df = pd.read_csv("Kalimati_Tarkari_Dataset.csv")
df.head()

/tmp/ipython-input-2146517307.py:1: DtypeWarning: Columns (3,4,5) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("Kalimati_Tarkari_Dataset.csv")


Commodity       Date Unit Minimum Maximum Average
0   Tomato Big(Nepali)  6/16/2013   Kg      35      40    37.5
1  Tomato Small(Local)  6/16/2013   Kg      26      32    29.0
2           Potato Red  6/16/2013   Kg      20      21    20.5
3         Potato White  6/16/2013   Kg      15      16    15.5
4   Onion Dry (Indian)  6/16/2013   Kg      28      30    29.0

In [73]:
df.shape

(280862, 6)

In [74]:
df.isnull().sum()

Commodity    0
Date         0
Unit         0
Minimum      0
Maximum      0
Average      0
dtype: int64

In [75]:
df = df.drop(['Unit'],axis=1)

In [76]:
df.head()

Commodity       Date Minimum Maximum Average
0   Tomato Big(Nepali)  6/16/2013      35      40    37.5
1  Tomato Small(Local)  6/16/2013      26      32    29.0
2           Potato Red  6/16/2013      20      21    20.5
3         Potato White  6/16/2013      15      16    15.5
4   Onion Dry (Indian)  6/16/2013      28      30    29.0

In [77]:
df['Date']

0          6/16/2013
1          6/16/2013
2          6/16/2013
3          6/16/2013
4          6/16/2013
             ...    
280857    2023-09-28
280858    2023-09-28
280859    2023-09-28
280860    2023-09-28
280861    2023-09-28
Name: Date, Length: 280862, dtype: object

In [78]:
df['Date'] = pd.to_datetime(
    df['Date'],
    format='mixed'
)


In [79]:
df.isnull().sum()

Commodity    0
Date         0
Minimum      0
Maximum      0
Average      0
dtype: int64

In [80]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 280862 entries, 0 to 280861
Data columns (total 5 columns):
 #   Column     Non-Null Count   Dtype         
---  ------     --------------   -----         
 0   Commodity  280862 non-null  object        
 1   Date       280862 non-null  datetime64[ns]
 2   Minimum    280862 non-null  object        
 3   Maximum    280862 non-null  object        
 4   Average    280862 non-null  object        
dtypes: datetime64[ns](1), object(4)
memory usage: 10.7+ MB


In [81]:
df['year'] = df['Date'].dt.year
df['month'] = df['Date'].dt.month

df.head()

Commodity       Date Minimum Maximum Average  year  month
0   Tomato Big(Nepali) 2013-06-16      35      40    37.5  2013      6
1  Tomato Small(Local) 2013-06-16      26      32    29.0  2013      6
2           Potato Red 2013-06-16      20      21    20.5  2013      6
3         Potato White 2013-06-16      15      16    15.5  2013      6
4   Onion Dry (Indian) 2013-06-16      28      30    29.0  2013      6

In [82]:
df['month'].unique()

array([ 6,  7,  8,  9, 10, 11, 12,  1,  2,  3,  4,  5], dtype=int32)

In [83]:
df['year'].unique()

array([2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023],
      dtype=int32)

In [84]:
new_df = df.drop('Date',axis=1)

In [85]:
new_df

Commodity   Minimum   Maximum   Average  year  month
0         Tomato Big(Nepali)        35        40      37.5  2013      6
1        Tomato Small(Local)        26        32      29.0  2013      6
2                 Potato Red        20        21      20.5  2013      6
3               Potato White        15        16      15.5  2013      6
4         Onion Dry (Indian)        28        30      29.0  2013      6
...                      ...       ...       ...       ...   ...    ...
280857  Tomato Small(Indian)  Rs 45.00  Rs 55.00  Rs 50.00  2023      9
280858   Tomato Small(Local)  Rs 50.00  Rs 60.00  Rs 55.00  2023      9
280859  Tomato Small(Tunnel)  Rs 60.00  Rs 75.00  Rs 69.00  2023      9
280860              Turnip A  Rs 70.00  Rs 80.00  Rs 75.00  2023      9
280861    Water Melon(Green)  Rs 50.00  Rs 60.00  Rs 56.67  2023      9

[280862 rows x 6 columns]

In [86]:
df['Commodity']

0           Tomato Big(Nepali)
1          Tomato Small(Local)
2                   Potato Red
3                 Potato White
4           Onion Dry (Indian)
                  ...         
280857    Tomato Small(Indian)
280858     Tomato Small(Local)
280859    Tomato Small(Tunnel)
280860                Turnip A
280861      Water Melon(Green)
Name: Commodity, Length: 280862, dtype: object

In [87]:
new_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 280862 entries, 0 to 280861
Data columns (total 6 columns):
 #   Column     Non-Null Count   Dtype 
---  ------     --------------   ----- 
 0   Commodity  280862 non-null  object
 1   Minimum    280862 non-null  object
 2   Maximum    280862 non-null  object
 3   Average    280862 non-null  object
 4   year       280862 non-null  int32 
 5   month      280862 non-null  int32 
dtypes: int32(2), object(4)
memory usage: 10.7+ MB


In [88]:
price_cols = ['Minimum', 'Maximum', 'Average']

for col in price_cols:
    new_df[col] = pd.to_numeric(
        new_df[col].astype(str).str.replace(r'[^0-9.]', '', regex=True)

    )

In [89]:
new_df['Minimum'].dtype

dtype('float64')

In [90]:
new_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 280862 entries, 0 to 280861
Data columns (total 6 columns):
 #   Column     Non-Null Count   Dtype  
---  ------     --------------   -----  
 0   Commodity  280862 non-null  object 
 1   Minimum    280862 non-null  float64
 2   Maximum    280862 non-null  float64
 3   Average    280862 non-null  float64
 4   year       280862 non-null  int32  
 5   month      280862 non-null  int32  
dtypes: float64(3), int32(2), object(1)
memory usage: 10.7+ MB


In [91]:
new_df['Price_Range'] = new_df['Maximum'] - new_df['Minimum']

In [92]:
new_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 280862 entries, 0 to 280861
Data columns (total 7 columns):
 #   Column       Non-Null Count   Dtype  
---  ------       --------------   -----  
 0   Commodity    280862 non-null  object 
 1   Minimum      280862 non-null  float64
 2   Maximum      280862 non-null  float64
 3   Average      280862 non-null  float64
 4   year         280862 non-null  int32  
 5   month        280862 non-null  int32  
 6   Price_Range  280862 non-null  float64
dtypes: float64(4), int32(2), object(1)
memory usage: 12.9+ MB


In [93]:
new_df['Commodity'].unique()

array(['Tomato Big(Nepali)', 'Tomato Small(Local)', 'Potato Red',
       'Potato White', 'Onion Dry (Indian)', 'Carrot(Local)',
       'Cabbage(Local)', 'Cauli Local', 'Raddish Red',
       'Raddish White(Local)', 'Brinjal Long', 'Brinjal Round',
       'Cow pea(Long)', 'Green Peas', 'French Bean(Local)',
       'Soyabean Green', 'Bitter Gourd', 'Bottle Gourd',
       'Pointed Gourd(Local)', 'Snake Gourd', 'Smooth Gourd',
       'Sponge Gourd', 'Pumpkin', 'Squash(Long)', 'Turnip', 'Okara',
       'Christophine', 'Brd Leaf Mustard', 'Spinach Leaf', 'Cress Leaf',
       'Mustard Leaf', 'Fenugreek Leaf', 'Onion Green', 'Mushroom(Kanya)',
       'Asparagus', 'Neuro', 'Brocauli', 'Sugarbeet', 'Drumstick',
       'Red Cabbbage', 'Lettuce', 'Celery', 'Parseley', 'Fennel Leaf',
       'Mint', 'Turnip A', 'Tamarind', 'Bamboo Shoot', 'Tofu', 'Gundruk',
       'Apple(Jholey)', 'Banana', 'Lime', 'Pomegranate', 'Mango(Maldah)',
       'Grapes(Green)', 'Water Melon(Green)', 'Sweet Orange', 'Pineappl

In [94]:
import category_encoders as ce

In [46]:
pip install category_encoders

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 85.9/85.9 kB 3.0 MB/s eta 0:00:00


In [95]:
X = new_df.drop(columns=['Average'])
y = new_df['Average']

In [96]:
X.head()

Commodity  Minimum  Maximum  year  month  Price_Range
0   Tomato Big(Nepali)     35.0     40.0  2013      6          5.0
1  Tomato Small(Local)     26.0     32.0  2013      6          6.0
2           Potato Red     20.0     21.0  2013      6          1.0
3         Potato White     15.0     16.0  2013      6          1.0
4   Onion Dry (Indian)     28.0     30.0  2013      6          2.0

In [97]:
y.head()

0    37.5
1    29.0
2    20.5
3    15.5
4    29.0
Name: Average, dtype: float64

In [98]:
from sklearn.model_selection import train_test_split

In [99]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [100]:
encoder = ce.TargetEncoder(cols=['Commodity'])

In [101]:
X_train['Commodity_enc'] = encoder.fit_transform(X_train['Commodity'], y_train)
X_test['Commodity_enc'] = encoder.transform(X_test['Commodity'], y_test)

In [102]:
X_train.head()

Commodity  Minimum  Maximum  year  month  Price_Range  \
174237        Christophine     25.0     30.0  2020      9          5.0   
236523        Garlic Green    350.0    400.0  2022      6         50.0   
209696  Onion Dry (Indian)     68.0     70.0  2021     10          2.0   
812         Soyabean Green     38.0     40.0  2013      7          2.0   
24733            Asparagus    200.0    250.0  2014      8         50.0   

        Commodity_enc  
174237      31.817949  
236523     108.035021  
209696      47.195363  
812         77.192261  
24733      402.192167

In [103]:
X_train = X_train.drop(columns=['Commodity'])
X_test = X_test.drop(columns=['Commodity'])

In [104]:
X_train.head()

Minimum  Maximum  year  month  Price_Range  Commodity_enc
174237     25.0     30.0  2020      9          5.0      31.817949
236523    350.0    400.0  2022      6         50.0     108.035021
209696     68.0     70.0  2021     10          2.0      47.195363
812        38.0     40.0  2013      7          2.0      77.192261
24733     200.0    250.0  2014      8         50.0     402.192167

In [105]:
X_test.head()

Minimum  Maximum  year  month  Price_Range  Commodity_enc
266288    140.0    150.0  2023      4         10.0     122.843128
65927     270.0    280.0  2016      4         10.0     284.531155
248247     70.0     80.0  2022     11         10.0      98.777720
172619    215.0    220.0  2020      8          5.0     232.797328
260373    180.0    200.0  2023      3         20.0     143.871897

In [106]:
y.head()

0    37.5
1    29.0
2    20.5
3    15.5
4    29.0
Name: Average, dtype: float64

In [107]:
import xgboost as xgb

In [108]:
model = xgb.XGBRegressor(
    n_estimators=500,
    learning_rate=0.1,
    max_depth=7,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42,
    tree_method='hist',  # fast for large dataset
    n_jobs=-1
)

In [109]:
model.fit(
    X_train,
    y_train,
    eval_set=[(X_test, y_test)],
    verbose=50
)

[0]	validation_0-rmse:87.65898
[50]	validation_0-rmse:2.49203
[100]	validation_0-rmse:2.57100
[150]	validation_0-rmse:2.49198
[200]	validation_0-rmse:2.46734
[250]	validation_0-rmse:2.58567
[300]	validation_0-rmse:2.23845
[350]	validation_0-rmse:2.30136
[400]	validation_0-rmse:2.56680
[450]	validation_0-rmse:2.54682
[499]	validation_0-rmse:2.68758


XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=0.8, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=0.1, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=7,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=500,
             n_jobs=-1, num_parallel_tree=None, ...)

In [111]:
y_pred = model.predict(X_test)

In [112]:
y_pred

array([145.4534  , 275.0473  ,  75.65933 , ..., 204.96523 ,  47.493412,
        47.486084], dtype=float32)

In [113]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
mae = mean_absolute_error(y_test, y_pred)
rmse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f"MAE  : {mae:.2f}")
print(f"RMSE : {rmse:.2f}")
print(f"R²   : {r2:.4f}")

MAE  : 0.21
RMSE : 7.22
R²   : 0.9992


In [114]:
import joblib

In [115]:
joblib.dump(model, 'xgboost_price_model.pkl')

['xgboost_price_model.pkl']

In [116]:
joblib.dump(encoder, 'commodity_target_encoder.pkl')

['commodity_target_encoder.pkl']

In [118]:
import pandas as pd

data = pd.DataFrame({
    "Minimum": [20],
    "Maximum": [50],
    "year": [2025],
    "month": [5],
    "Price_Range": [30],
    "Commodity_enc": [35.5],
})

# Predict
output = model.predict(data)
print("Predictions:", output)


Predictions: [45.142082]
